### ISSUE TITLE
Why does protonup flatpak need `device=all` permission?

### ISSUE THREAD

**Issue by Apacelus** [flathub/net.davidotek.pupgui2#14]
Any particular reasons for this flatpak have access to all devices?

**Comment by DavidoTek** [comment]
It is necessary for ProtonUp-Qt to access connected gamepads (or the SteamDeck joysticks) which can be used to navigate the user interface without mouse and keyboard or touch screen.

Sadly, as far as I know, there is no other way to do this (see https://github.com/flatpak/xdg-desktop-portal/issues/536)

**Comment by Apacelus** [comment]
Huh, I didnt even know that was possible at all!

With that knowledge it makes more sense for this permission
