### ISSUE TITLE
Theming is broken since the latest update

### ISSUE THREAD

**Issue by zocker-160** [flathub/net.davidotek.pupgui2#2]
pre commit e37d4182455fe4a9611849ac1b2c4ef093c08e67
![grafik](https://user-images.githubusercontent.com/36563538/160590290-c5160b41-65ed-46be-80c4-f325cf0c18de.png)

latest update
![grafik](https://user-images.githubusercontent.com/36563538/160590329-cc173bd5-f609-4281-974a-4e0f7b01e09e.png)

My system is Kubuntu 20.04 LTS.

**Comment by DavidoTek** [comment]
ProtonUp-Qt's GUI framework was upgraded to PySide6. Some themes don't support Qt6 yet, we need to wait for them to add support. See e.g. https://bugs.kde.org/show_bug.cgi?id=448450

For now you can enable a "manual" darkmode here: `About > Color Scheme > Dark`

**Comment by zocker-160** [comment]
ah understood, so this is not a Flatpak problem then. Should we keep this issue open?

**Comment by DavidoTek** [comment]
Yes, the same applies for the [AppImage version](https://github.com/DavidoTek/ProtonUp-Qt/releases/).

I think we can close the issue for now. I may reopen it if there is some tweeking necessary for the Flatpak version/some "workaround" available.
